### ISSUE TITLE
Some profile missing photoUrl

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/member-api#16]
example: http://api.topcoder.com/v5/members/tourist missing `photoUrl`

Original issue: https://github.com/topcoder-platform/community-app/issues/4275

**Comment by urwithat** [comment]
@luizrrodrigues - Have done analysis on member `tourist` data, I don't see any image been uploaded by the member.
I could add an image for the member, or you could request the member to add himself.

I don't see an issue with the photo upload feature of Topcoder. Will close the ticket, feel free to reopen or reach out to me for clarification on the analysis conducted.
