### ISSUE TITLE
member-api: "homeCountryCode" value is coming null 

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/member-api#24]
Example - recently created user - https://api.topcoder-dev.com/v5/members/sachin220401 
Before activation member api call - 
<img width="1315" alt="Screenshot 2021-04-22 at 3 22 46 PM" src="https://user-images.githubusercontent.com/6467888/116066148-5e7d0b80-a6a5-11eb-8c2c-4b1bb6f256db.png">
After activation - 
<img width="597" alt="Screenshot 2021-04-22 at 3 21 48 PM" src="https://user-images.githubusercontent.com/6467888/116066142-5c1ab180-a6a5-11eb-9466-0dd2640bd936.png">

**Comment by urwithat** [comment]
Fixed

**Comment by urwithat** [comment]
The fix where done if different repos:
https://github.com/appirio-tech/identity-service/commit/2b900940221a1cbb87a87a5daad172fe9ae3113c
https://github.com/topcoder-platform/member-account-processor/commit/bf3c4db53444f6a73e40482b39e1bda86961c855

**Comment by lakshmiathreya** [comment]
https://github.com/appirio-tech/identity-service/issues/39
