### ISSUE TITLE
Traits API returns profile_picture: false even if Profile picture is uploaded

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/member-api#55]
**Steps**
Go to any users profile settings : https://www.topcoder-dev.com/settings/profile/
Upload a profile picture
Call {{URL}}/members/<handle>/traits?traitIds=onboarding_checklist API 
See the response

As soon as uploading a profile picture, it will return profile_picture: true but after sometimes it is set to false

example user: taasintake6

**Comment by vikasrohit** [comment]
@sdgun issue should be logged in https://github.com/topcoder-platform/onboarding-processor
