### ISSUE TITLE
Searching for `52code` failing in production

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/member-api#86]
In production, searching for `52code` returns no results.

Sample query:

https://api.topcoder.com/v5/members/autocomplete?term=52code

and response:

```
[]
```

The same query for `ghostar` returns a number of results:

https://api.topcoder.com/v5/members/autocomplete?term=ghostar

```
[
    {
        "userId": "151743",
        "handle": "Ghostar",
        "firstName": "Justin",
        "lastName": "Gasper"
    },
    {
        "userId": "22823436",
        "handle": "ghostar0315183",
        "firstName": "leo",
        "lastName": "xing"
    },
    {
        "userId": "41064624",
        "handle": "Ghostar2020",
        "firstName": "Justin",
        "lastName": "Gasper"
    },
    {
        "userId": "40618516",
        "handle": "Ghostark",
        "firstName": "sai",
        "lastName": "kumar"
    },
    {
        "userId": "40633688",
        "handle": "GhostArnaud",
        "firstName": "Wanet",
        "lastName": "Arnaud"
    }
]
```

Note that `52code` does return when using the endpoint directly instead of searching:

https://api.topcoder.com/v5/members?handle=52code

```
[
    {
        "userId": 90194308,
        "handle": "52code",
        "handleLower": "52code",
        "status": "ACTIVE",
        "photoURL": null,
        "homeCountryCode": "AFG",
        "competitionCountryCode": "AFG",
        "description": "",
        "tracks": [
            "DEVELOP"
        ],
        "maxRating": {
            "rating": 1332,
            "subTrack": "CODE",
            "track": "DEVELOP",
            "ratingColor": "#616BD5"
        },
        "createdAt": 1646384070217,
        "updatedAt": 1656603298157,
 ...
```

### Fix

Please investigate why this particular search may be failing.  We need to:

1. Document a similar failing query in the dev environment (https://api.topcoder-dev.com), where we know a handle exists, but the search returns no results
2. Apply a fix
3. Do the same test in step 1, showing the now working query

**Comment by jpeg22** [comment]
We could union the results of both API calls if we aren't able to move to a v5 API or fix the problem quickly.

**Comment by jmgasper** [comment]
Fixed in dev
